nameSuffix: "-frontend"
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: whereami-grpc-frontend
resources:
- ../k8s-grpc
patches:
- path: cm-flag.yaml
  target:
    kind: ConfigMap