
# Argo 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whereami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/whereami.git' # Change this to your repo
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true