# Argo 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whereami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/deploywithjoy/kubecon24-demos.git'
    targetRevision: HEAD
    path: whereami/argo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: whereami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true