apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: whereami
build:
  artifacts:
    - image: gcr.io/google-samples/whereami:v1.2.22
      context: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml