apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-pipeline-run
spec:
  pipelineRef:
    name: deploy-pipeline
  params:
    - name: IMAGE
      value: gcr.io/your-project/whereami:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: your-pvc